FROM ubuntu:22.04
LABEL author="Martin Eberlein"

USER root

RUN apt-get -y update \
    && apt-get -y upgrade \
    && apt-get -y install \
    git \
    bash \
    fish \
    gcc \
    g++ \
    make \
    cmake \
    clang \
    wget \
    python3 \
    python3-pip \
    vim \
    curl

# RUN useradd -ms /bin/bash avicenna

# USER avicenna
WORKDIR /home/avicenna

RUN pip3 install --upgrade pip wheel setuptools
RUN pip3 install scipy fuzzingbook

ENV TZ=Europe/Madrid
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get install -y tzdata

RUN apt-get -y install make build-essential libssl-dev zlib1g-dev \
libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

ENV HOME="/root"
RUN git clone --depth=1 https://github.com/pyenv/pyenv.git $HOME/.pyenv
ENV PYENV_ROOT="$HOME/.pyenv"
ENV PATH="$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH"

RUN git clone https://github.com/martineberlein/avicenna.git
WORKDIR /home/avicenna/avicenna

RUN git pull
RUN git checkout dev
RUN pip3 install -e .[dev]


WORKDIR /home/avicenna
RUN git clone https://github.com/smythi93/Tests4Py.git
WORKDIR /home/avicenna/Tests4Py

RUN git pull
RUN pip3 install .

CMD ["fish"]
